package br.com.gabifontainhas.techchallenge.dto;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
@Schema(name = "ApiError", description = "Standardized error response following RFC 9457 - Problem Detail")
public final class ApiErrorDoc {

    public record UserNotFoundDTO(
            @Schema(example = "404", description = "The HTTP status code generated by the origin server")
            int status,

            @Schema(example = "Not Found", description = "A short, human-readable summary of the problem type")
            String title,

            @Schema(example = "/v1/users/1", description = "A URI reference that identifies the specific occurrence of the problem")
            String instance,

            @Schema(example = "User not found", description = "A human-readable explanation specific to this occurrence of the problem")
            String detail
    ) {
    }

    public record UserNotFoundByNameDTO(
            @Schema(example = "404", description = "The HTTP status code generated by the origin server")
            int status,

            @Schema(example = "Not Found", description = "A short, human-readable summary of the problem type")
            String title,

            @Schema(example = "/v1/users/user", description = "A URI reference that identifies the specific occurrence of the problem")
            String instance,

            @Schema(example = "User not found", description = "A human-readable explanation specific to this occurrence of the problem")
            String detail
    ) {
    }

    public record IncorrectPasswordDTO(
            @Schema(example = "422", description = "The HTTP status code generated by the origin server")
            int status,

            @Schema(example = "Unprocessable Content", description = "A short, human-readable summary of the problem type")
            String title,

            @Schema(example = "/v1/users/1/password", description = "A URI reference that identifies the specific occurrence of the problem")
            String instance,

            @Schema(example = "The current password provided is incorrect", description = "A human-readable explanation specific to this occurrence of the problem")
            String detail
    ) {
    }

    public record OwnerEmailAlreadyExistsDTO(
            @Schema(example = "422", description = "The HTTP status code generated by the origin server")
            int status,

            @Schema(example = "Unprocessable Content", description = "A short, human-readable summary of the problem type")
            String title,

            @Schema(example = "/v1/owners", description = "A URI reference that identifies the specific occurrence of the problem")
            String instance,

            @Schema(example = "E-mail already exist", description = "A human-readable explanation specific to this occurrence of the problem")
            String detail
    ) {
    }

    public record OwnerNotFoundDTO(
            @Schema(example = "404", description = "The HTTP status code generated by the origin server")
            int status,

            @Schema(example = "Not Found", description = "A short, human-readable summary of the problem type")
            String title,

            @Schema(example = "/v1/owners/1", description = "A URI reference that identifies the specific occurrence of the problem")
            String instance,

            @Schema(example = "User not found", description = "A human-readable explanation specific to this occurrence of the problem")
            String detail
    ) {
    }

    public record CustomerEmailAlreadyExistsDTO(
            @Schema(example = "422", description = "The HTTP status code generated by the origin server")
            int status,

            @Schema(example = "Unprocessable Content", description = "A short, human-readable summary of the problem type")
            String title,

            @Schema(example = "/v1/customers", description = "A URI reference that identifies the specific occurrence of the problem")
            String instance,

            @Schema(example = "E-mail already exist", description = "A human-readable explanation specific to this occurrence of the problem")
            String detail
    ) {
    }

    public record CustomerNotFoundDTO(
            @Schema(example = "404", description = "The HTTP status code generated by the origin server")
            int status,

            @Schema(example = "Not Found", description = "A short, human-readable summary of the problem type")
            String title,

            @Schema(example = "/v1/customers/1", description = "A URI reference that identifies the specific occurrence of the problem")
            String instance,

            @Schema(example = "User not found", description = "A human-readable explanation specific to this occurrence of the problem")
            String detail
    ) {
    }

    public record AuthenticationFailedDTO (
            @Schema(example = "401", description = "The HTTP status code generated by the origin server")
            int status,

            @Schema(example = "Unauthorized", description = "A short, human-readable summary of the problem type")
            String title,

            @Schema(example = "/v1/auth/login", description = "A URI reference that identifies the specific occurrence of the problem")
            String instance,

            @Schema(example = "Authentication Failed", description = "A human-readable explanation specific to this occurrence of the problem")
            String detail
    ) {
    }
}


